import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider as UIProvider} from "@/components/ui/provider"
import Header from "@/features/common/components/Header";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvier";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSessionProvider>
          <Header />
          <UIProvider>
            {children}
          </UIProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
