services:
  app:
    container_name: "note-for-debater"
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    tty: true
    environment:
      - TZ=Asia/Tokyo
      - ENV=${ENV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./app
        target: /app

  db:
    container_name: "note-for-debater-db"
    image: postgres:16.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    tty: true
    volumes:
      - postgres:/var/lib/posgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres: