services:
  app:
    container_name: "note-for-debater"
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    tty: true
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8082:8080
    volumes:
      - type: bind
        source: ./app
        target: /app
